name = "aurelio-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "aurelio"
database_id = "debbd535-295c-45f0-8a2f-358bc5c0941b"

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://aurelio.pages.dev"

[triggers]
crons = ["0 20 * * *"]
